<html>
<head>
<title>TestNG:  Login_Test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Login_Test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>7/2/0</td>
</tr><tr>
<td>Started on:</td><td>Thu Mar 29 13:09:25 IST 2018</td>
</tr>
<tr><td>Total time:</td><td>11 seconds (11142 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.milvik.mip.loginlogout.testrunner.MIP_Login_Test.loginTestFour()'><b>loginTestFour</b><br>Test class: com.milvik.mip.loginlogout.testrunner.MIP_Login_Test<br>Parameters: DA40, invalid, Your login attempt was not successful, try again.
Reason: Invalid Password</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at com.milvik.mip.loginlogout.testrunner.MIP_Login_Test.loginTestFour(MIP_Login_Test.java:152)
... Removed 29 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace500885941", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace500885941'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.milvik.mip.loginlogout.testrunner.MIP_Login_Test.loginTestFour(MIP_Login_Test.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>1</td>
<td>com.milvik.mip.loginlogout.testrunner.MIP_Login_Test@61832929</td></tr>
<tr>
<td title='com.milvik.mip.loginlogout.testrunner.MIP_Login_Test.loginTestSix()'><b>loginTestSix</b><br>Test class: com.milvik.mip.loginlogout.testrunner.MIP_Login_Test<br>Parameters: DA41, Tigo123!, Your login attempt was not successful, try again.Reason: User account is locked</td>
<td><div><pre>java.lang.AssertionError: expected [0] but found [1]
	at com.milvik.mip.loginlogout.testrunner.MIP_Login_Test.loginTestSix(MIP_Login_Test.java:201)
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1196963249", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1196963249'><pre>java.lang.AssertionError: expected [0] but found [1]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.testng.Assert.assertEquals(Assert.java:398)
	at com.milvik.mip.loginlogout.testrunner.MIP_Login_Test.loginTestSix(MIP_Login_Test.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>com.milvik.mip.loginlogout.testrunner.MIP_Login_Test@61832929</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.milvik.mip.loginlogout.testrunner.MIP_Login_Test.loginTestFive()'><b>loginTestFive</b><br>Test class: com.milvik.mip.loginlogout.testrunner.MIP_Login_Test<br>Parameters: DA41, invalid, Your login attempt was not successful, try again.Reason: User account is locked</td>
<td></td>
<td>2</td>
<td>com.milvik.mip.loginlogout.testrunner.MIP_Login_Test@61832929</td></tr>
<tr>
<td title='com.milvik.mip.loginlogout.testrunner.MIP_Login_Test.loginTestFour()'><b>loginTestFour</b><br>Test class: com.milvik.mip.loginlogout.testrunner.MIP_Login_Test<br>Parameters: invalid, Tele123!, Your login attempt was not successful, try again.
Reason: Bad credentials </td>
<td></td>
<td>1</td>
<td>com.milvik.mip.loginlogout.testrunner.MIP_Login_Test@61832929</td></tr>
<tr>
<td title='com.milvik.mip.loginlogout.testrunner.MIP_Login_Test.loginTestFour()'><b>loginTestFour</b><br>Test class: com.milvik.mip.loginlogout.testrunner.MIP_Login_Test<br>Parameters: , Tele123!, Please enter both user id and password.</td>
<td></td>
<td>0</td>
<td>com.milvik.mip.loginlogout.testrunner.MIP_Login_Test@61832929</td></tr>
<tr>
<td title='com.milvik.mip.loginlogout.testrunner.MIP_Login_Test.loginTestFour()'><b>loginTestFour</b><br>Test class: com.milvik.mip.loginlogout.testrunner.MIP_Login_Test<br>Parameters: DA40, , Please enter both user id and password.</td>
<td></td>
<td>0</td>
<td>com.milvik.mip.loginlogout.testrunner.MIP_Login_Test@61832929</td></tr>
<tr>
<td title='com.milvik.mip.loginlogout.testrunner.MIP_Login_Test.loginTestFour()'><b>loginTestFour</b><br>Test class: com.milvik.mip.loginlogout.testrunner.MIP_Login_Test<br>Parameters: DASH, PASS, Your login attempt was not successful, try again.
Reason: Bad credentials </td>
<td></td>
<td>1</td>
<td>com.milvik.mip.loginlogout.testrunner.MIP_Login_Test@61832929</td></tr>
<tr>
<td title='com.milvik.mip.loginlogout.testrunner.MIP_Login_Test.loginTestOne()'><b>loginTestOne</b><br>Test class: com.milvik.mip.loginlogout.testrunner.MIP_Login_Test</td>
<td></td>
<td>2</td>
<td>com.milvik.mip.loginlogout.testrunner.MIP_Login_Test@61832929</td></tr>
<tr>
<td title='com.milvik.mip.loginlogout.testrunner.MIP_Login_Test.loginTestThree()'><b>loginTestThree</b><br>Test class: com.milvik.mip.loginlogout.testrunner.MIP_Login_Test</td>
<td></td>
<td>0</td>
<td>com.milvik.mip.loginlogout.testrunner.MIP_Login_Test@61832929</td></tr>
</table><p>
</body>
</html>